name: "release-test"
on:
  push:
    branches:
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl version